[MOSIP-31019] Updated vidivi.py
mosip/release-script pull request #343
Opened 2024-06-24 08:18 UTC by Rakshithb1

2024-06-24 08:38 UTC, syedsalman3753 requested changes

2024-06-24 08:38 UTC, syedsalman3753 commented on release/vidivi/vidivi.py
> +
Please remove this and print docker hash id in destination existence section

2024-06-24 10:44 UTC, Rakshithb1 commented on release/vidivi/vidivi.py
> +
updated as requested

2024-06-24 13:23 UTC, syedsalman3753 approved these changes

2024-06-25 05:40 UTC, ckm007 commented
seems your update appends the logs every time to vidivi.log, instead it should overwrite the same and raise the PR.
lets seperate logger funtion.
also the image movement is serial ow.. lets move them parallely using concurrent.futures

2024-07-02 12:08 UTC, ckm007 commented on release/vidivi/vidivi.py
> +        srcregistryUrl = "https://registry.hub.docker.com/v2/"
take the value from variable where this value is default.

2024-07-02 12:08 UTC, merged